/** Same kit modules as Aviation-tab-frontend MedicineModules.js */
export const MODULES = [
  {
    id: "A",
    title: "Module A (Essential):",
    emoji: "💊",
    description:
      "Essential emergency medicines and first-response supplies for immediate onboard care.",
    defaultOpen: true,
    items: [
      { name: "Atropine ampoule 600 mcg /ml", usage: "Slow heart rate / Cardiac arrest", outOfStock: false },
      { name: "Adrenaline (Epinephrine) 1:1000 ampoule", usage: "Anaphylaxis", outOfStock: false },
      { name: "Epipen OR NEFFY", usage: "Anaphylaxis", outOfStock: true },
      { name: "Midozalam ( Buccal or Intranasal )", usage: "Seizure", outOfStock: false },
      { name: "Amiodarone Ampoule", usage: "Ventricular tachycardia / Fibrillation", outOfStock: false },
      { name: "Hydrocortisone sodium succinate 250 mg", usage: "Asthma", outOfStock: false },
      { name: "Diphenhydramine 50mgml", usage: "Allergy", outOfStock: false },
      { name: "Aspirin 300 mg tablets", usage: "Chest pain / Heart attack/ MI", outOfStock: false },
      { name: "GTN SPRAY 400 mcg", usage: "Angina", outOfStock: false },
      { name: "Salbutamol (Albuterol) inhaler", usage: "Asthma", outOfStock: false },
      { name: "Dextrose,50% injectable", usage: "Hypoglycemia / low blood sugar", outOfStock: false },
      { name: "Glucose gel ( 2 x tubes supplied)", usage: "Hypoglycemia / low blood sugar", outOfStock: false },
      { name: "TAB Paracetamol", usage: "Pain", outOfStock: false },
      { name: "TAB Loratidine", usage: "Allergy", outOfStock: false },
      { name: "Tab Ondesetron", usage: "Nausea and vomiting", outOfStock: false },
    ],
  },
  {
    id: "B",
    title: "Module B (Medication):",
    emoji: "💊",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt",
    defaultOpen: false,
    items: [
      { name: "Atropine Sulfate 600mcg /ml ampoule", usage: "", outOfStock: false },
      { name: "Adrenaline (Epinephrine) 1:1000 ampoule - IM", usage: "", outOfStock: false },
      { name: "Adrenaline (Epinephrine) 1:10,000 ampoule - IV", usage: "", outOfStock: false },
      { name: "Lidocaine 50mg /5 ml ampoule - IV", usage: "", outOfStock: false },
      { name: "Hydrocortisone Sodium succinate 250 gm", usage: "", outOfStock: false },
      { name: "Sodium chloride (Saline) 0.9% 20 ml for injection", usage: "", outOfStock: false },
      { name: "Aspirin 300 mg tablets", usage: "", outOfStock: false },
      { name: "GTN Spray 400mcg", usage: "", outOfStock: false },
      { name: "Salbutamol (Albuterol) inhaler", usage: "", outOfStock: false },
      { name: "Glucose gel - Glutose 15", usage: "", outOfStock: false },
      { name: "Paracetamol", usage: "", outOfStock: false },
      { name: "Antihistamine tablets", usage: "", outOfStock: false },
      { name: "Diphenhydramine injectable 50 mg/ml", usage: "", outOfStock: false },
      { name: "SPACER DEVICE for Salbutamol", usage: "", outOfStock: false },
      { name: "180 Injection needle", usage: "", outOfStock: false },
      { name: "230 Injection needle", usage: "", outOfStock: false },
      { name: "Drawing needle blunt", usage: "", outOfStock: false },
      { name: "5ml Syringe", usage: "", outOfStock: false },
      { name: "Gauze Square", usage: "", outOfStock: false },
    ],
  },
  {
    id: "C",
    title: "Module C (Airway):",
    emoji: "💊",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt",
    defaultOpen: false,
    items: [
      { name: "Oropharyngeal Airway Set Child 50mm", usage: "", outOfStock: false },
      { name: "Oropharyngeal Airway Small Adult 70mm", usage: "", outOfStock: false },
      { name: "Oropharyngeal Airway Set Adult 90mm", usage: "", outOfStock: false },
      { name: "Bag-Valve-Mask (Adult)", usage: "", outOfStock: false },
      { name: "Pocket Mask with one-way valve", usage: "", outOfStock: false },
      { name: "Manual Suction Device", usage: "", outOfStock: false },
      { name: "Oxygen Mask with tubing (Adult)", usage: "", outOfStock: false },
    ],
  },
  {
    id: "D",
    title: "Module D (Circulation):",
    emoji: "💊",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt",
    defaultOpen: false,
    items: [
      { name: "IV Cannula 22G / IV Wing", usage: "", outOfStock: false },
      { name: "IV Giving Set", usage: "", outOfStock: false },
      { name: "IV Bung / Reflux valve (safiste)", usage: "", outOfStock: false },
      { name: "0.9% Normal Saline 500 ml", usage: "", outOfStock: false },
      { name: "Tagarderm film", usage: "", outOfStock: false },
      { name: "Tourniquet (Disposable)", usage: "", outOfStock: false },
      { name: "Gauze Square", usage: "", outOfStock: false },
      { name: "Documents folder", usage: "", outOfStock: false },
      { name: "Instructions manual", usage: "", outOfStock: false },
      { name: "Splint", usage: "", outOfStock: false },
      { name: "Sharps Container", usage: "", outOfStock: false },
    ],
  },
];
